package ir;
import java.util.List;

// Pretty printer for instruction sequences generated by munch
public class MunchPrinter {
    private TempMap tempMap;  
    
    public MunchPrinter() {
        this.tempMap = new DefaultTempMap();
    }
    
    public MunchPrinter(TempMap tempMap) {
        this.tempMap = tempMap;
    }
  
    public void print(String functionName, List<Instr> instructions) {
        System.out.println("Function: " + functionName);
        
        for (int i = 0; i < instructions.size(); i++) {
            System.out.printf("%3d: %s%n", i, formatInstruction(instructions.get(i)));
        }
        
        printStatistics(instructions);
        System.out.println();
    }
    
    private String formatInstruction(Instr instr) {
        String result = instr.assem;  
        
        List<Temp> defs = instr.def();
        for (int i = 0; i < defs.size() && i < 3; i++) {
            String placeholder = "`d" + i;           // `d0, `d1, etc.
            String tempName = tempMap.tempMap(defs.get(i));
            if (tempName != null) {
                result = result.replace(placeholder, tempName);
            }
        }
        
        List<Temp> uses = instr.use();
        for (int i = 0; i < uses.size() && i < 3; i++) {
            String placeholder = "`s" + i;         
            String tempName = tempMap.tempMap(uses.get(i));
            if (tempName != null) {
                result = result.replace(placeholder, tempName);
            }
        }
        
        return result;
    }
    
    private void printStatistics(List<Instr> instructions) {
        int totalInstructions = instructions.size();
        int arithmeticOps = 0;    // add, sub, mul, div, and, or, xor
        int memoryOps = 0;        // lw, sw, la (memory access instructions)
        int controlFlowOps = 0;   // branches, jumps, calls
        int moveOps = 0;          // register-to-register moves
        int labelCount = 0;       // labels (branch/jump targets)
        
        for (Instr instr : instructions) {
            String assem = instr.assem.toLowerCase();
            
            if (instr instanceof LabelInstr) {
                labelCount++;
            } else if (instr instanceof MOVE) {
                moveOps++;
            } else if (assem.contains("add") || assem.contains("sub") || 
                      assem.contains("mul") || assem.contains("div") ||
                      assem.contains("and") || assem.contains("or") || assem.contains("xor")) {
                arithmeticOps++;
            } else if (assem.contains("lw") || assem.contains("sw") || 
                      assem.contains("lb") || assem.contains("sb") ||
                      assem.contains("la")) {
                memoryOps++;
            } else if (assem.contains("beq") || assem.contains("bne") || 
                      assem.contains("blt") || assem.contains("bgt") ||
                      assem.contains("jal") || assem.contains("jr") || assem.contains("j ")) {
                controlFlowOps++;
            }
        }
        
        System.out.println("Statistics:");
        System.out.println("  Total instructions: " + totalInstructions);
        System.out.println("  Arithmetic ops:     " + arithmeticOps);
        System.out.println("  Memory ops:         " + memoryOps);  
        System.out.println("  Control flow:       " + controlFlowOps);
        System.out.println("  Move ops:           " + moveOps);
        System.out.println("  Labels:             " + labelCount);
        
        if (totalInstructions > 0) {
            double memoryRatio = (double) memoryOps / totalInstructions * 100;
            double moveRatio = (double) moveOps / totalInstructions * 100;
            System.out.printf("  Memory ops ratio:   %.1f%%%n", memoryRatio);
            System.out.printf("  Move ops ratio:     %.1f%%%n", moveRatio);
        }
    }
    
    public void printAssembly(String functionName, List<Instr> instructions) {
        System.out.println("# Function: " + functionName);
        
        for (Instr instr : instructions) {
            if (instr instanceof LabelInstr) {
                // Labels flush left (no indentation)
                System.out.println(formatInstruction(instr));
            } else {
                // Instructions indented for readability
                System.out.println("    " + formatInstruction(instr));
            }
        }
        System.out.println();
    }
    
    public void printAssemblyFile(String functionName, List<Instr> instructions) {
        System.out.println(".text");                           // Code section
        System.out.println(".globl " + functionName);          // Export function name
        System.out.println();
        
        for (Instr instr : instructions) {
            if (instr instanceof LabelInstr) {
                System.out.println(formatInstruction(instr));   // Labels flush left
            } else {
                System.out.println("    " + formatInstruction(instr));  // Instructions indented
            }
        }
        
        System.out.println();
    }
    
    public void printDebug(String functionName, List<Instr> instructions) {
        System.out.println("=== DEBUG: Function " + functionName + " ===");
        
        for (int i = 0; i < instructions.size(); i++) {
            Instr instr = instructions.get(i);
            System.out.printf("%3d: %-30s", i, formatInstruction(instr));
            
            List<Temp> uses = instr.use();
            List<Temp> defs = instr.def();
            
            if (!uses.isEmpty() || !defs.isEmpty()) {
                System.out.print(" [");
                if (!defs.isEmpty()) {
                    System.out.print("def:" + defs);
                }
                if (!uses.isEmpty()) {
                    if (!defs.isEmpty()) System.out.print(", ");
                    System.out.print("use:" + uses);
                }
                System.out.print("]");
            }
            
            System.out.println();
        }
        System.out.println();
    }
    
    public void printComparison(String name1, List<Instr> instructions1, 
                               String name2, List<Instr> instructions2) {
        System.out.println("=== Instruction Sequence Comparison ===");
        System.out.printf("%-20s: %d instructions%n", name1, instructions1.size());
        System.out.printf("%-20s: %d instructions%n", name2, instructions2.size());
        
        if (instructions1.size() != instructions2.size()) {
            int diff = instructions2.size() - instructions1.size();
            System.out.printf("Difference: %+d instructions (%.1f%%)%n", 
                            diff, (double)diff / instructions1.size() * 100);
        }
        System.out.println();
    }
}
